### ISSUE TITLE
how can I use -insecure?

### ISSUE THREAD

**Issue by kabegithub** [joedwards32/CS2#17]
I want to run the server as VAC disabled because I want to play custom maps with my friends.  I put CS2_ADDITIONAL_ARGS="-insecure +exec server.cfg" as shown but the log of container says "SV:  VAC secure mode is activated."
How can I disable it?

**Comment by joedwards32** [comment]
Thanks for the issue report.

Supplying `-insecure` without `+exec server.cfg` seems to work.

`docker run -it -v ~/cs2-data:/home/steam/cs2-dedicated/ --env STEAMUSER=***** --env STEAMPASS=***** --env CS2_PW=changeme --env CS2_RCONPW=changeme --name cs2-dedicated -env CS2_ADDITIONAL_ARGS='-insecure' --publish $YOURIP:27015:27015/udp --publish $YOURIP:27015:27015/tcp joedwards32/cs2`

Log excerpt shows:

```
command line arguments:
-dedicated -port 27015 -console -usercon -maxplayers_override 10 +game_type 0 +game_mode 1 +mapgroup mg_active +map de_inferno -insecure
execing server_default.cfg
execing server.cfg
execing gamemode_casual.cfg
SV:  VAC secure mode disabled.
```
However, when I include `+exec server.cfg` I see the same problem as you. This argument is superfluous because server.cfg is executed by default anyway.

I'll have a play to see if argument ordering is important here.

**Comment by kabegithub** [comment]
Thank you for your response. I've confirmed working without `+exec server.cfg`.

**Comment by joedwards32** [comment]
@kabegithub I fixed this in passing under https://github.com/joedwards32/CS2/pull/21

The problem was I hadn't used the `eval` BaSH built in to parse the argument strings correctly.
