### ISSUE TITLE
I want to run commands as root on this container

### ISSUE THREAD

**Issue by kabegithub** [joedwards32/CS2#50]
I want to use [CounterStrikeSharp](https://docs.cssharp.dev/) but it requires  libicu / icu-libs / libicu-dev.
I want to install these packages but the permission denied via current user on this container.

**Comment by joedwards32** [comment]
Hey, I'm already collaborating with CSSharp on this issue, see: #40.

If you need this urgently (can't wait for the above PR), you can always build your own derivative image which contains the dependencies.

**Comment by kabegithub** [comment]
Thank you for your reply.
I haven't notice that PR.
And CSSharp works well with that method.

**Comment by Apfelwurm** [comment]
@kabegithub in regards to counterstrikesharp, i've commented in #40 again.
But i would also love to see the option to run a root command on startup, since we want to add an ssh connection to the inside of the container, to connect the debugger to the plugin that we build. Currently we have to build up on your container to implement that.

**Comment by joedwards32** [comment]
> @joedwards32 would you accept a pr for that one? :)

Best practice is not to run as root within the container. Steps requiring root privileges should ideally happen in a build stage.

Some container runtimes, like OpenShift, won't let you execute root UID entrypoints.

I think the best approach if you require that kind of thing is to use my image as a base image and layer a new build stage on top.
