### ISSUE TITLE
Ubuntu 22.04 unable to deploy container.

### ISSUE THREAD

**Issue by austinkschmitz** [joedwards32/CS2#75]
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

Issue:
When running docker container. `docker run --name=cs2 -e SRCDS_TOKEN="TOKEN" -p 27015:27015/tcp -p 27015:27015/udp -p 27020:27020/tcp joedwards32/cs2`

`Error! App '730' state is 0x202 after update job.`
`cp: cannot create regular file '/home/steam/cs2-dedicated/game/csgo/cfg/server.cfg': No such file or directory`
`sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory`
`entry.sh: line 60: cd: /home/steam/cs2-dedicated/game/bin/linuxsteamrt64: No such file or directory`
`pre-hook: noop`
`Starting CS2 Dedicated Server`
`entry.sh: line 93: ./cs2: No such file or directory`

I get error "entry.sh: line 93: ./cs2: No such file or directory"

Same error when using docker-compose.

The container is built but does not run. 
` docker run --name=cs2 -e SRCDS_TOKEN="TOKEN" -p 27015:27015/tcp -p 27015:27015/udp -p 27020:27020/tcp joedwards32/cs2
docker: Error response from daemon: Conflict. The container name "/cs2" is already in use by container "CONTAINER_GUID". You have to remove (or rename) that container to be able to reuse that name.`

Reading through the read.me and I'm not sure if I'm following the procedure 100%

**Comment by TobiWo** [comment]
I'm not the maintainer but it looks like that the entry.sh script has an issue on your side. The question is why. I guess the creator @joedwards32 needs to help here.

The second error is most likely due to the fact that you started the compose and want to start the general docker command after that but this time the container called `cs2` is still running. You need to shutdown the container first with `docker compose --file examples/docker-compose.yml down`.

**Comment by TobiWo** [comment]
Ok, I guess I found what your issue is @austinkschmitz.

1. I recommend to use the data persistence mode. See README `Running using a bind mount for data persistence on container recreation:`
1. If you have multiple subfolders you need to `chmod` them all to 777. E.g. if you have directory `/home/user/cs2/cs2-data` navigate to `/home/user` and execute `chmod -R 777 cs2`
1. Don't forget to adapt the directory structure in the docker command after the `-v` flag (if you use a different folder structure than in the README commands)
1. In this specific case the docker command would be: `docker run -d --name=cs2 -e SRCDS_TOKEN={YOURTOKEN} -v /home/user/cs2/cs2-data:/home/steam/cs2-dedicated/ -p 27015:27015/tcp -p 27015:27015/udp -p 27020:27020/tcp joedwards32/cs2`

**Comment by joedwards32** [comment]
Thanks for providing support, @TobiWo.

`Error! App '730' state is 0x202 after update job.` definitely indicates that there was insufficient persistent storage to download all of the CS2 game files.
